apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-vault.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cert-vault.name" . }}
    helm.sh/chart: {{ include "cert-vault.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.ports.business }}
      targetPort: business
      protocol: TCP
      name: business
    - port: {{ .Values.service.ports.management }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    app.kubernetes.io/name: {{ include "cert-vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}