apiVersion: v2
name: cert-vault
description: A Helm chart for CertVault self-signed SSL certificate management platform backend server.
home: https://github.com/gregperlinli/cert-vault
icon: https://raw.githubusercontent.com/gregPerlinLi/CertVault/refs/heads/main/frontend/public/favicon.svg
keywords:
  - cert-vault
  - self-sign
  - certificate
  - management
type: application
version: 2.5.3
appVersion: "2.5.3"
kubeVersion: ">= 1.20.0-0"
maintainers:
  - email: lihaolin13@outlook.com
    name: gregPerlinLi
sources:
  - https://github.com/gregperlinli/cert-vault
  - https://github.com/gregperlinli/certvault-charts
dependencies:
  - name: redis
    version: 20.11.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.internal
  - name: mysql
    version: 12.3.2
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.internal
  - name: postgresql
    version: 16.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.internal
annotations:
  artifacthub.io/links: |
    - name: support
      url: https://github.com/gregPerlinLi/CertVault/issues
  artifacthub.io/screenshots: |
    - title: Dashboard
      url: https://raw.githubusercontent.com/gregPerlinLi/CertVault/main/docs/img/Screenshot2.png
    - title: CA Certificate Management
      url: https://raw.githubusercontent.com/gregPerlinLi/CertVault/main/docs/img/Screenshot1.png
    - title: SSL Certificate Management
      url: https://raw.githubusercontent.com/gregPerlinLi/CertVault/main/docs/img/Screenshot3.png
    - title: User Management
      url: https://raw.githubusercontent.com/gregPerlinLi/CertVault/main/docs/img/Screenshot4.png