apiVersion: v2
name: cert-vault
description: A Helm chart for CertVault self-signed SSL certificate management platform backend server.
home: https://github.com/gregperlinli/cert-vault
icon: https://raw.githubusercontent.com/gregPerlinLi/CertVault/refs/heads/main/frontend/public/favicon.svg
keywords:
  - cert-vault
  - self-sign
  - certificate
  - management
type: application
version: 0.7.0
appVersion: "0.7.0"
maintainers:
  - email: lihaolin13@outlook.com
    name: gregPerlinLi
sources:
  - https://github.com/gregperlinli/cert-vault
  - https://github.com/gregperlinli/certvault-charts
dependencies:
  - name: redis
    version: 20.11.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.internal
  - name: mysql
    version: 12.3.2
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.internal