## Docker image configuration
## @param image.registry [default: ghcr.io] The URL of the Docker image registry
## @param image.repository [default: gregperlinli/certvault] The repository name in the Docker image registry
## @skip image.tag The tag of the Docker image to be used (e.g., latest, v1.0.0)
## @param image.pullPolicy [default: IfNotPresent] The policy for pulling the Docker image
##
image:
  registry: ghcr.io
  repository: gregperlinli/certvault
  tag: ""
  pullPolicy: IfNotPresent

## Global configuration
## @param global.defaultStorageClass Global default StorageClass for Persistent Volume(s)
## @param global.storageClass DEPRECATED: use global.defaultStorageClass instead
##
global:
  defaultStorageClass: "standard"
  storageClass: ""

## Number of replicas for the deployment
## @param replicaCount [default: 1] The number of pod replicas to be created for the deployment
##
replicaCount: 1

## Spring Boot application configuration
## @param springBoot.profile [default: dev] The active profile for the Spring Boot application
## @param springBoot.logging.level.com_gregperlinli_certvault [default: debug] Logging level for the com.gregperlinli.certvault package
## @param springBoot.logging.level.org_springframework [default: warn] Logging level for the org.springframework package
## @param springBoot.javaOpts JVM options to be passed to the Java Virtual Machine
##
springBoot:
  profile: dev
  logging:
    level:
      com_gregperlinli_certvault: debug
      org_springframework: warn
  javaOpts:
    # Maximum heap size
    - "-Xmx512m"
    # Initial heap size
    - "-Xms256m"
    # Use Z Garbage Collector
    - "-XX:+UseZGC"
    # Target collection interval in milliseconds
    - "-XX:ZCollectionInterval=120"
    # Allocation spike tolerance
    - "-XX:ZAllocationSpikeTolerance=4"
    # Disable proactive mode
    - "-XX:-ZProactive"
    # Enable heap dump on OutOfMemoryError
    - "-XX:+HeapDumpOnOutOfMemoryError"
    # Path to heap dump file
    - "-XX:HeapDumpPath=./errorDump.hprof"

## Server configuration
## @param server.baseUrl The base URL of the server
##
server:
  baseUrl: "http://127.0.0.1:1888"

## OIDC configuration
## @param oidc.enabled Whether OIDC authentication is enabled
## @param oidc.provider.name The name of the OIDC provider
## @param oidc.provider.clientId The client ID for OIDC authentication
## @param oidc.provider.clientSecret The client secret for OIDC authentication
## @param oidc.provider.authorizationUri The authorization endpoint URL
## @param oidc.provider.tokenUri The token endpoint URL
## @param oidc.provider.userInfoUri The user info endpoint URL
## @param oidc.provider.jwkSetUri The JWK set endpoint URL
## @param oidc.provider.usernameAttributes The attribute used to map username
##
oidc:
  enabled: true
  provider:
    name: "oidc"
    clientId: "oidc-client-id"
    clientSecret: "oidc-client-secret"
    authorizationUri: "https://oidc-provider.example.com/auth"
    tokenUri: "https://oidc-provider.example.com/token"
    userInfoUri: "https://oidc-provider.example.com/userinfo"
    jwkSetUri: "https://oidc-provider.example.com/certs"
    usernameAttributes: "preferred_username"

## Initialization configuration
## @param init.superadmin.username The username for the superadmin user
## @param init.superadmin.displayName The display name for the superadmin user
## @param init.superadmin.email The email address for the superadmin user
## @param init.superadmin.password The password for the superadmin user
##
init:
  superadmin:
    username: "superadmin"
    displayName: "Default Superadmin"
    email: "superadmin@certvault.example"
    password: "changeme"

## Encryption configuration
## @param encrypt.rsa.key.publicKey The public key used for RSA encryption
## @param encrypt.rsa.key.privateKey The private key used for RSA decryption
##
encrypt:
  rsa:
    key:
      publicKey: "changeme"
      privateKey: "changeme"

## API documentation configuration
## @param apiDocs.enabled Whether the API documentation is enabled
##
apiDocs:
  enabled: true

## Service configuration
## @param service.ports.business [default: 1888] Business port for the application
## @param service.ports.management [default: 1999] Management port for the application
##
service:
  ports:
    business: 1888
    management: 1999

## Service Monitor configuration for Prometheus
## @param serviceMonitor.enabled [default: true] Whether the service monitor is enabled
## @param serviceMonitor.path [default: /actuator/prometheus] Path for Prometheus metrics endpoint
## @param serviceMonitor.port [default: 1999] Port for Prometheus metrics endpoint
##
serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  port: 1999

## Resource configuration for the application
## @param resources.requests.cpu [default: 500m] CPU request for the application container
## @param resources.requests.memory [default: 512Mi] Memory request for the application container
## @param resources.limits.cpu [default: 1000m] CPU limit for the application container
## @param resources.limits.memory [default: 1024Mi] Memory limit for the application container
##
resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1024Mi"

## Redis configuration
## @param redis.internal [default: true] Whether to use an internal Redis instance (true) or an external Redis instance (false)
## @param redis.architecture [default: standalone] The architecture of the Redis deployment (standalone or cluster)
## @param redis.auth.enabled [default: true] Whether authentication is enabled for Redis
## @param redis.auth.password [default: your-redis-password] The password used for Redis authentication
## @param redis.metrics.enabled [default: true] Whether to enable metrics for Redis
## @param redis.metrics.serviceMonitor.enabled [default: false] Whether to enable Service Monitor for Prometheus metrics
## @param redis.external.host [default: redis-master.example.com] Hostname or IP address of the external Redis instance
## @param redis.external.port [default: 6379] Port number of the external Redis instance
## @param redis.external.database [default: 0] Database index to use
## @param redis.external.auth.enabled [default: true] Whether authentication is enabled for the external Redis instance
## @param redis.external.auth.password [default: your-redis-password] Password for the external Redis instance
##
redis:
  internal: true
  auth:
    enabled: true
    password: "your-redis-password"
  architecture: standalone
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
  external:
    host: redis-master.example.com
    port: "6379"
    database: "0"
    auth:
      enabled: true
      password: "your-redis-password"

## Database configuration
## @param database.type [default: mysql] The type of database to use (mysql, postgresql)
database:
  type: postgresql

## MySQL configuration
## @param mysql.internal [default: false] Whether to use an internal MySQL instance (true) or an external MySQL instance (false)
## @param mysql.architecture [default: standalone] The architecture of the MySQL deployment (standalone or cluster)
## @param mysql.auth.rootPassword [default: your-mysql-root-password] Root user password for internal MySQL deployment
## @param mysql.auth.database [default: certvault] Database name to use (both internal and external)
## @param mysql.auth.username [default: certvault] Username for MySQL access (used in internal deployment)
## @param mysql.auth.password [default: your-mysql-password] Password for the MySQL user (used in internal deployment)
## @param mysql.metrics.enabled [default: true] Whether to enable metrics for MySQL
## @param mysql.metrics.serviceMonitor.enabled [default: false] Whether to enable Service Monitor for Prometheus metrics
## @param mysql.external.host [default: localhost] Hostname/IP of external MySQL instance
## @param mysql.external.port [default: 3306] Port of external MySQL instance
## @param mysql.external.database [default: certvault] Database name for external MySQL
## @param mysql.external.username [default: certvault] Username for external MySQL access
## @param mysql.external.password [default: password] Password for external MySQL user
##
mysql:
  internal: false
  auth:
    rootPassword: "your-mysql-root-password"
    database: certvault
    username: certvault
    password: "your-mysql-password"
  architecture: standalone
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
  external:
    host: localhost
    port: 3306
    database: certvault
    username: certvault
    password: "password"

## PostgreSQL configuration
## @param postgresql.internal [default: false] Whether to use an internal PostgreSQL instance (true) or an external PostgreSQL instance (false)
## @param postgresql.auth.postgresPassword [default: your-postgres-password] PostgreSQL root user password for internal PostgreSQL deployment
## @param postgresql.auth.database [default: certvault] Database name to use (both internal and external)
## @param postgresql.auth.username [default: certvault] Username for PostgreSQL access (used in internal deployment)
## @param postgresql.auth.password [default: your-postgres-password] Password for the PostgreSQL user (used in internal deployment)
## @param postgresql.metrics.enabled [default: true] Whether to enable metrics for PostgreSQL
## @param postgresql.metrics.serviceMonitor.enabled [default: false] Whether to enable Service Monitor for Prometheus metrics
## @param postgresql.external.host [default: localhost] Hostname/IP of external PostgreSQL instance
## @param postgresql.external.port [default: 5432] Port of external PostgreSQL instance
## @param postgresql.external.database [default: certvault] Database name for external PostgreSQL
## @param postgresql.external.username [default: certvault] Username for PostgreSQL access (used in internal deployment)
## @param postgresql.external.password [default: password] Password for PostgreSQL user (used in internal deployment)
##
postgresql:
  internal: false
  auth:
    postgresPassword: "your-postgres-password"
    database: certvault
    username: certvault
    password: "your-postgres-password"
  architecture: standalone
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
  external:
    host: localhost
    port: 5432
    database: certvault
    username: certvault
    password: "password"

## Ingress configuration
## @param ingress.enabled [default: false] Whether ingress is enabled
## @param ingress.annotations Annotations for the ingress
## @param ingress.hosts.host [default: chart-example.local] Hostname for the ingress
## @param ingress.hosts.paths.path [default: /] Path for the ingress
## @param ingress.hosts.paths.pathType [default: ImplementationSpecific] Path type for the ingress
## @param ingress.ingressClassName [default: nginx] Ingress class name
## @skip ingress.tls TLS configuration for the ingress
##
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  ingressClassName: "nginx"
  # tls:
  #   - secretName: my-tls-secret
  #     hosts:
  #      - chart-example.local

## Node Selector configuration
## @param nodeSelector A map of key-value pairs to select nodes for pod scheduling. Each entry specifies a node label and its required value to ensure pods are scheduled on specific nodes.
##
nodeSelector: {}
##  E.g.
##  kubernetes.io/arch: amd64
##  beta.kubernetes.io/os: linux

## Node Affinity configuration
## @param nodeAffinity Defines node affinity rules based on node labels to control where pods are scheduled
## @param nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution Mandatory node affinity conditions that must be met during scheduling but ignored post-scheduling
## @param nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms List of node selector terms, each containing one or more match conditions
## @param nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms.matchExpressions List of matching expressions defining label criteria
## @param nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms.matchExpressions.key Label key to match
## @param nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms.matchExpressions.operator Operator (e.g., In, NotIn)
## @param nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms.matchExpressions.values Allowed label values list
nodeAffinity: {}
##  E.g.
##  requiredDuringSchedulingIgnoredDuringExecution:
##    nodeSelectorTerms:
##      - matchExpressions:
##        - key: kubernetes.io/arch
##          operator: In
##          values:
##            - amd64
##        - key: beta.kubernetes.io/os
##          operator: In
##          values:
##             - linux

## Pod Affinity configuration
## @param podAffinity Defines pod affinity rules based on other pods' labels to control topological relationships
## @param podAffinity.requiredDuringSchedulingIgnoredDuringExecution Mandatory pod affinity conditions that must be met during scheduling but ignored post-scheduling
## @param podAffinity.requiredDuringSchedulingIgnoredDuringExecution.labelSelector Label selector to match other pods' labels
## @param podAffinity.requiredDuringSchedulingIgnoredDuringExecution.labelSelector.matchExpressions List of matching expressions
## @param podAffinity.requiredDuringSchedulingIgnoredDuringExecution.labelSelector.matchExpressions.key Label key to match
## @param podAffinity.requiredDuringSchedulingIgnoredDuringExecution.labelSelector.matchExpressions.operator Operator (e.g., In, NotIn)
## @param podAffinity.requiredDuringSchedulingIgnoredDuringExecution.labelSelector.matchExpressions.values Allowed label values list
## @param podAffinity.requiredDuringSchedulingIgnoredDuringExecution.topologyKey Key to determine topology domain (e.g., availability zone)
podAffinity: {}
##  E.g.
##  requiredDuringSchedulingIgnoredDuringExecution:
##    - labelSelector:
##        matchExpressions:
##          - key: security
##            operator: In
##            values:
##              - S1
##        topologyKey: topology.kubernetes.io/zone
